version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - SECRET_KEY=changeme
      - DB_NAME=easytsd
      - DB_USER=easytsd
      - DB_PASSWORD=easytsd
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: easytsd
      POSTGRES_PASSWORD: easytsd
      POSTGRES_DB: easytsd
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
